# 不推荐在 Github Actions 上运行此脚本
# 由于 Github Actions 服务器位于海外，可能导致账号风控等问题
# 推荐使用国内的 CI/CD 服务或本地/自有服务器运行
name: 自动签到

on:
    schedule:
        - cron: '0 20 * * *'  # run at 20:00 every day
    workflow_dispatch:

jobs:
    run-main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                    python-version: '3.11'
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt --break-system-packages
            - name: Create .env file
              run: |
                    touch .env
                    echo "ACCOUNT_PHONE=${{ secrets.ACCOUNT_PHONE }}" >> .env
                    echo "ACCOUNT_AUTH=${{ secrets.ACCOUNT_AUTH }}" >> .env
                    echo "SHARE=${{ secrets.SHARE }}" >> .env
                    echo "UPLOAD=${{ secrets.UPLOAD }}" >> .env
                    echo "DIR_ID=${{ secrets.DIR_ID }}" >> .env
                    echo "SHARE_FILENAME=${{ secrets.SHARE_FILENAME }}" >> .env
            - name: Run main.py
              run: python main.py